### PR TITLE
For merge - Bobby

### PR DESCRIPTION
**Pull request by Hang-Bobby-Zou**
- Added a new file "bragg_tmm_object_apodized_1310.py" to allow apodization of Kappa/dwidth
- In "bragg_tmm_object_apodized_1310.py", removed segment setting since we cannot do this trick with apodization structure
- In "bragg_tmm_object_apodized_1310.py", added parameter GaussianIndex for necessary for apodization
- In "bragg_tmm_object_apodized_1310.py", removed the randomization of width function in "def Grating_Matrix" since it was not used previous, can add back on easily
- In "bragg_tmm_object_apodized_1310.py", added Kappa fit just for 1310 bragg grating of the specific dimension
- In "bragg_tmm_object_apodized_1310.py", updated the lambda_bragg for 1310 bragg

- In "waveguide_cml.lsf" changed the sweep waveguide width for a 1310 waveguide of 350nm x 220nm

- The files show now have waveguide variability params txt for both 1310 and 1550

TODO:
- Add type checking, I was not quite sure how to do it elegantly so currently this is not added for this PR, I will do another PR later with more added

### CODE REVIEW

**Comment by mustafacc** [comment]
Thanks a lot Bobby, it loosk great

**Comment by mustafacc** [comment]
I'm trying the script with apodizatio = 0 (ie uniform) and comparing it to the original uniform script, i'm seeing a large difference. any thoughts on why?
original script:
image

your update:
image

**Comment by Hang-Bobby-Zou** [comment]
Hi @mustafacc I have adjusted the kappa fit to a new second order equation

**Comment by mustafacc** [comment]
Thanks. i cleaned up the code. there are a bunch of unused variables, unused arguements, etc. 
i also reimplemented it such that there is only a single bragg object for both 1310 and 1550. 1310 is now a subclass of 1550.
https://github.com/mustafacc/SiEPIC_Bragg_workshop/commit/1050e9f194a5f3ddc04ef9387813e3cd2e76ff39

**Pull request merged**
